defaults:
  - override hydra/launcher: submitit_slurm


hydra:
  launcher:
    tasks_per_node: ${hardware.world_size}
    gpus_per_node: ${hardware.world_size}
    cpus_per_task: 4    
    partition: gpu

data:
  train_on: base
  base:
    name: CIFAR10
    batch_size: 256
    drop_last: True
    shuffle: True
    split: train
    num_workers: -1
    transforms:
      view1:
      - name: RandomResizedCrop
        kwargs:
          size: 32
          scale:
            - 0.2
            - 1.0
          interpolation: bicubic
      - name: RandomHorizontalFlip
        kwargs:
          p: 0.5
      - name: ColorJitter
        kwargs:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.2
          hue: 0.1
        p: 0.8
      - name: RandomGrayscale
        kwargs:
          p: 0.2
  test_out:
    name: CIFAR10
    batch_size: 256
    drop_last: False
    num_workers: -1
    split: test
    transforms:
      view1:
        - name: ToTensor
        - name: Normalize
          kwargs:
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]

model:
  name: Supervised
  backbone_model: resnet9

optim:
  epochs: 200
  batch_size: 256
  lr: 1.0
  optimizer: LARS

hardware:
  seed: 0
  float16: true
  world_size: 1
  